services:
    postgres_db:
        image: postgres
        #restart: always
        ports:
          - "5432:5432"
        volumes:
          - "./postgres_data:/var/lib/postgresql/data"
        env_file:
          - ./db.env
#        environment:
 #         POSTGRES_DB: ${POSTGRES_DB}
  #        POSTGRES_USER: ${POSTGRES_USER}
   #       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

